### ISSUE TITLE
"Resource Reload Failed" After Launch with Frostiful

### ISSUE THREAD

**Issue by TheDeathlyCow** [IMB11/Fog#14]
I received two reports, one in TheDeathlyCow/frostiful#100 and one on Discord, of a "Resource Reload Failed" toast appearing after launch with Frostiful installed, and after some investigation, it was discovered that this only occurred when Fog was installed. 

The issue seems to occur when the Frost Wand item renderer tries to reload, and fetch the Frost Wand model from the appropriate render layer. For whatever reason, the Frost Wand model layer is not registered when this happens with Fog installed. I have checked that everything is correctly registered through Fabric API, and I believe it is (you can check [here](https://github.com/TheDeathlyCow/frostiful/blob/main/src/main/java/com/github/thedeathlycow/frostiful/client/render/FrostWandItemRenderer.java), [here](https://github.com/TheDeathlyCow/frostiful/blob/main/src/main/java/com/github/thedeathlycow/frostiful/client/model/FEntityModelLayers.java), and [here](https://github.com/TheDeathlyCow/frostiful/blob/main/src/main/java/com/github/thedeathlycow/frostiful/FrostifulClient.java)), so I think the issue has to do with some of the resource reloading going on here. Maybe there is an extra "reload event" being fired? 

Note that this error does *not* seem to be fatal, the game does not crash and all of Frostiful's resources still seem to work just fine - it is just this weird error appearing on launch and in the log. 

This is the log that was given to me in the GitHub report: https://mclo.gs/C9OErrM
Here is my log, with just Fog and Frostiful (and Frostiful's dependencies): https://mclo.gs/ElF0Lh6 

This was tested on Minecraft 1.21, Fabric Loader 0.16.0, and Fabric API 0.102.0

I really like the look of this mod, by the way, will be adding to my normal set of vanilla client mods :)

**Comment by Steveplays28** [comment]
Hi, thanks for the report! I'll take a look, might be a timing issue or similar.

**Comment by ExDrill** [comment]
This exact issue happens with Guarding, since it also uses a special item renderer for its Netherite Shield.
https://github.com/Team-Abode/guarding/issues/17
