### ISSUE TITLE
Incompatibility with BetterClouds.

### ISSUE THREAD

**Issue by iekiekkeikei** [IMB11/Fog#17]
version 1.20.1
loader fabric
Modlist
- YetAnotherConfigLib
- Better Clouds
- Fog
- Fabric API
- Mod Menu

When walking around with the weather set to rain, clouds disappear and appear.
Enabling the disableRaininessEffect solves this problem.
![2024-08-11_17 11 35](https://github.com/user-attachments/assets/b097e9ba-40e9-4f00-97b9-b3e4d0a56159)
![2024-08-11_17 11 39](https://github.com/user-attachments/assets/5acd0e51-017c-4e71-9f02-53b2d18085e3)

**Comment by Steveplays28** [comment]
Hi, thank you for the report. I'll take a look when I have time.

**Comment by Qendolin** [comment]
This is something that I have to fix on my end. The issue occurs because BC expects vanilla fog and doesn't adjust it's calculation when the Fog mod is installed. I could just add a check if the fog mod is loaded or not.

**Comment by Steveplays28** [comment]
Fixed by Qendolin in Better Clouds.
