### ISSUE TITLE
Strange fog artifacts on sunset after updating to 1.3.1

### ISSUE THREAD

**Issue by vico93** [IMB11/Fog#19]
https://github.com/user-attachments/assets/0b7f7d32-a1fa-4ac4-9c49-232d5e86b7bc

**Comment by IMB11** [comment]
Does this occur on 1.3.0 as well?

**Comment by vico93** [comment]
Testing right now with 1.3.0

I'm getting only this artifacts during daylight depending of the angle i'm staring on the window (i'm using Continuity/Indium btw):

https://github.com/user-attachments/assets/e97d7522-acb5-4d46-9d20-7e19d1a45c4f

**Comment by IMB11** [comment]
This might be todo with the new point system we introduced in 1.3.0 to detect if the player was underground.

**Comment by IMB11** [comment]
Might be fixed in the next version, testing on Discord now.
