### ISSUE TITLE
Opening the config menu crashes the game.

### ISSUE THREAD

**Issue by Verbina29** [IMB11/Fog#20]
[crash-2024-08-17_15.40.21-client.txt](https://github.com/user-attachments/files/16646453/crash-2024-08-17_15.40.21-client.txt)
[latest.log](https://github.com/user-attachments/files/16646454/latest.log)

**Comment by Steveplays28** [comment]
Hi Verbina39, thank you for the report.
I'll take a look in a few days when I have time.

**Comment by IMB11** [comment]
This might be fixed in the next update (1.4.0) - if it still occurs after updating, please reopen the issue.

**Comment by Verbina29** [comment]
yeah no it still does it

**Comment by Shragdhar** [comment]
This was tagged as completed but still no fix has been implemented. The issue was reopened on Oct. 22.
