### ISSUE TITLE
Fog has failed to load correctly

### ISSUE THREAD

**Issue by Skrengus** [IMB11/Fog#21]
[crash-2024-08-22_17.10.33-fml.txt](https://github.com/user-attachments/files/16719534/crash-2024-08-22_17.10.33-fml.txt)

![2024-08-22_17 10 40](https://github.com/user-attachments/assets/cdd7f833-212b-4194-89a9-4f17461f1087)

Error when launching my NeoForge 1.21 instance. I've tested the mod on both a lightly modded instance of the same version and a fresh install with only Fog and YetAnotherConfigLib. Same results for each. Crash report is from the clean install if that makes any difference. Am I missing something here?

**Comment by IMB11** [comment]
You need to install the MRU library mod. Not sure why neoforge isn't telling you.

**Comment by Skrengus** [comment]
Thank you it works now! I download mods through Prism Launcher and Fog didn't add in any dependencies like other mods seem to do. Weird. Anyway, thanks again and hope your day is well. :-)
