### ISSUE TITLE
Odd fog behaviour when resurfacing from sea-level underwater

### ISSUE THREAD

**Issue by anoomolu** [IMB11/Fog#22]
Hiya! I've really enjoyed playing with this mod, thanks for polishing it so much ^^

I noticed that the fog can get a bit weird when resurfacing from water at or below sea-level. Below are some screenshots comparing vanilla fog (with Simple Fog Control) and Fog immediately after resurfacing.

Vanilla/SFC:
![image](https://github.com/user-attachments/assets/2669db17-a508-4112-b16c-9473706d39e9)
![image](https://github.com/user-attachments/assets/a72d744e-4f0e-4cf4-addb-78daf650bb04)

Fog:
![image](https://github.com/user-attachments/assets/d21b384a-cbbf-4855-a641-59e1572f3d29)
![image](https://github.com/user-attachments/assets/f2d18bb8-b293-49f7-95f0-35b31d31166e)

Probably to do with the underground detection for cave fog.

**Comment by IMB11** [comment]
> Probably to do with the underground detection for cave fog.
Yep, you're spot on, will fix now.

**Comment by IMB11** [comment]
Will be fixed in the next update :+1:
