### ISSUE TITLE
Biome colored fog is too bright at night

### ISSUE THREAD

**Issue by Contra-S** [IMB11/Fog#25]
The biome colored fog looks way too bright, it almost looks like it's daytime. It'd be great if the colors were toned down at night.

![2024-08-30_19 55 28](https://github.com/user-attachments/assets/ae69d04a-0dc1-41b5-ad8a-ab2f28dc4c36)

![2024-08-30_19 55 43](https://github.com/user-attachments/assets/8890998a-13f2-4694-a43d-13354a720855)

**Comment by IMB11** [comment]
Yup, this will be fixed in the next update.
