### ISSUE TITLE
flashing occurs when i jump at a certain point in the end + no assets folder

### ISSUE THREAD

**Issue by DylanM124** [IMB11/Fog#39]
### Have you read the information above?

- [X] Yes

### Provide your logs.

- Log of assets folder not generating (Forge 1.20.1): https://mclo.gs/tV0lf4o
- Log of crash due to accessing fog's config in-game: https://mclo.gs/g4R8P13

### Describe your issue.

going between y61-y62 creates a flashing effect. the fog comes closer and rendered chunks decrease, then reverts back to normal. im using nullscape, so im not sure if thats a normal ground y-level. as for the assets folder, 1.3 and below creates an assets folder for me. 1.4 and above i dont get one. yes i tried deleting the fog config folder and restarting the game, nothing. one odd thing is if i try to access the config of fog in-game, it crashes my game. no other mod does that

https://github.com/user-attachments/assets/cb191b36-7d81-49c7-a193-91605ebf136f

**Comment by Steveplays28** [comment]
I can reproduce the `config/fog/assets/` folder missing on Fabric 1.21.

**Comment by Steveplays28** [comment]
Both issues should be fixed in Fog [`v1.5.0](https://github.com/IMB11/Fog/releases/latest).
