### ISSUE TITLE
Feature Request: Add Compatibility With True Darkness

### ISSUE THREAD

**Issue by minhty-fresh** [IMB11/Fog#48]
Would you consider adding compatibility with True Darkness? 
This is one of the forks that is still being maintained https://modrinth.com/mod/true-darkness-refabricated

I think this would involve adding an optional config for new moon night fog color and interpolating between that and the normal night fog color depending on the moon phase. No need for any actual integration with the mod.

Personally, I actually really liked the old bright blue nighttime fog color from this mod, I just think it would have been nice to also have it be compatible with darker nights. Here's an example of what this could look like, I just manually adjusted the night fog colors to get this effect.

![true-dark-fog-example](https://github.com/user-attachments/assets/49b6a4ce-6498-4f97-a436-065703cff823)

If you're open to it, I'd also be happy to try submitting my own pull request to add this feature.

**Comment by minhty-fresh** [comment]
I ended up trying my hand at a pull request to add this feature https://github.com/IMB11/Fog/pull/49

**Comment by IMB11** [comment]
Will be supported in `v1.6.0`
