### ISSUE TITLE
Feature Request: Disable mod by Biome

### ISSUE THREAD

**Issue by LPFan12** [IMB11/Fog#51]
Nether Fog seems to break with this mod enabled(at least for me), which is usually not an issue because the mod contains a setting to disable its functions per dimension. An issue with this, however, is that it is infact possible to have Nether fog in the Overworld by generating a Nether biome there(In Vanilla, this can be done through the "Single Biome"-worldtype). 

This is bad, because it quickly gets nigh unplayable without just disabling the mod entirely, which is an annoying toggle to constantly adjust when changing worlds. An option to disable it in specific biomes would both fix this issue and give the user more detailed control over its usage in general, so it seems like a win-win if it is technically possible to implement.

**Comment by IMB11** [comment]
This will replace disabled dimensions in v1.6.0
