### ISSUE TITLE
Fog Compatibility with Sodium

### ISSUE THREAD

**Issue by iRaqhy** [IMB11/Fog#53]
There's an issue with the fog color when using Sodium/Embeddium. The blue hue fog is missing at night, and the fog color doesn't change after it rains. Also, Minecraft crashes every time I open the configuration in the mod menu.

![2024-11-01_12 30 14](https://github.com/user-attachments/assets/aca9662e-0691-413c-9f2e-4b0cfcc41af8)

**Comment by IMB11** [comment]
This isnt a sodium bug, the blue hue night colours have been changed from the previous fog update, you will need to make a resource pack to change the blue hue back.

**Comment by IMB11** [comment]
We'd need logs to diagnose your other issues, please make a new issue for those.
