### ISSUE TITLE
Prevents game from loading, and the CF page links to the wrong repo

### ISSUE THREAD

**Issue by vizthex123** [IMB11/Fog#9]
Here's my log:
[latest.log](https://github.com/user-attachments/files/16485378/latest.log)

And I noticed the "issues" tab on the CF page links to [this repo](https://github.com/IMB11/FogLooksGoodNow/issues) instead of this one.

**Comment by IMB11** [comment]
We'll look into it for 1.0.4

**Comment by IMB11** [comment]
Fixed in 1.0.5 - doing CF stuff now
